#!/bin/bash
#
# Generates docs/manual-testing.md from this script.
#
# The markdown content lives in heredocs below. The reason this script
# exists is that tracey can parse r[verify ...] annotations from shell
# scripts but not from markdown files. Each step is a small function
# (immediately called) so tracey sees proper symbol boundaries for the
# annotations.
#
# Usage:
#   scripts/gen-manual-testing.sh          # prints to stdout
#   scripts/gen-manual-testing.sh --check  # exits non-zero if docs/manual-testing.md is stale
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$REPO_ROOT/docs/manual-testing.md"

generate() {

preamble() {
    cat << 'MD'
<!-- Generated by scripts/gen-manual-testing.sh -- do not edit by hand -->

# Manual Pre-Release Testing

This document defines the manual testing procedure that must be completed
before each release. It covers tests that cannot be fully automated in CI,
primarily due to hardware requirements (TPM, USB, real network, bare-metal
boot).

The procedure is designed to be completed by one person in a single session.
Steps are ordered so that earlier steps produce artifacts needed by later
steps. Do not skip steps unless marked optional.

Throughout this document, "native arch" means the architecture of the
machine you are running the tests on (typically amd64).

## Prerequisites

Before starting, ensure the following are available:

- A Linux workstation with `sudo`, KVM, and at least 40 GB of free disk
  space.
- All build dependencies installed (`just check-deps` must pass).
- A Tailscale account with the ability to generate an ephemeral, reusable
  auth key.
- VirtualBox (or another full UEFI VM hypervisor) installed.
- A USB flash drive (8 GB minimum) that can be wiped.
- A bare-metal UEFI machine for the final hardware test. This cannot be
  the build workstation -- the installer will wipe the target disk.

MD
}
preamble

# r[verify image.output.raw]
# r[verify image.output.vmdk]
# r[verify image.output.qcow2]
# r[verify image.output.checksum]
step1() {
    cat << 'MD'
## Step 1: Build Images and ISO

Build all image variants and the ISO for your native architecture.

```
just arch=amd64 variant=cloud build
just arch=amd64 variant=metal build
just arch=amd64 iso
```

Verify that all expected output files exist:

```
just arch=amd64 variant=cloud verify-outputs
just arch=amd64 variant=metal verify-outputs
```

MD
}
step1

step2() {
    cat << 'MD'
## Step 2: Run Automated Tests Locally

Run the full automated test suite, including tests that CI also runs. This
catches regressions before proceeding to the slower manual steps.

```
just arch=amd64 variant=cloud test
just arch=amd64 variant=metal test
just arch=amd64 iso-test-structure
```

MD
}
step2

# r[verify installer.container.swtpm]
step3() {
    cat << 'MD'
## Step 3: Run Container Install Tests (All Variants)

CI can only run the cloud container tests because LUKS key operations
require a kernel keyring that is not available in GitHub Actions runners.
Run the full container test suite locally, which includes all metal
scenarios (TPM via swtpm, keyfile) and cloud scenarios.

```
just arch=amd64 test-container-isolation
just arch=amd64 test-container-install
```

All scenarios must pass. Pay attention to the TPM scenario
(`metal-tpm-swtpm`); if `swtpm` or the `tpm_vtpm_proxy` kernel module is
not available, load the module (`sudo modprobe tpm_vtpm_proxy`) and retry.

MD
}
step3

# r[verify installer.finalise.tailscale-auth]
# r[verify installer.tui.tailscale-netcheck+2]
# r[verify installer.tui.network-check+4]
step4() {
    cat << 'MD'
## Step 4: Interactive Installer with Real Tailscale Key

This verifies that the Tailscale authentication flow works end-to-end with
a real auth key, and that the TUI is usable by a human.

1. Generate an **ephemeral, reusable** Tailscale auth key from the
   Tailscale admin console.
2. Launch the interactive installer trial:

   ```
   just arch=amd64 try-installer
   ```

3. Walk through every TUI screen:
   - **Welcome screen**: verify the description text renders correctly in
     ASCII. Press `n` to open the network check screen, confirm that
     connectivity checks and `tailscale netcheck` run and display results.
     Press `Esc` to return, then `Enter` to proceed.
   - **Disk selection**: confirm the loopback disk is listed with its
     size and model. Select it and press `Enter`.
   - **Disk encryption**: select "Full-disk encryption, not bound to
     hardware" (keyfile). Verify the explanation text updates. Press
     `Enter`.
   - **Hostname**: select "Static hostname", type a test hostname (e.g.
     `manual-test-01`), press `Enter`.
   - **Login screen**: type and confirm a password. Press `Alt+t` and
     paste the real Tailscale auth key. Press `Enter` to return. Verify
     the yellow `*` indicator appears next to the Tailscale hint.
   - **Timezone**: type to filter (e.g. `Pacific`), select a timezone,
     press `Enter`.
   - **Network results**: verify the pre-summary network screen shows
     results. Press `Enter`.
   - **Confirmation**: verify the summary lists the correct disk,
     encryption mode, hostname, and that a recovery passphrase is
     displayed. Type `yes` to confirm.
   - **Progress**: watch the progress bar advance through partition
     writes and post-write steps.
   - **Completion**: verify the recovery passphrase is shown again. Press
     `Enter`.

4. After the installer exits, check the installer log for Tailscale
   authentication results. It should show a successful `tailscale up`
   or a firstboot key file write (depending on network availability
   inside the container).
5. Remove the test node from the Tailscale admin console.

**Acceptance criteria**: the installer completes without error, all TUI
screens render correctly with no Unicode replacement characters, and the
Tailscale auth key is accepted.

MD
}
step4

# r[verify iso.format]
# r[verify iso.boot.uefi]
# r[verify iso.boot.autostart+3]
# r[verify iso.live-boot]
# r[verify iso.offline]
# r[verify installer.tui.welcome+5]
# r[verify installer.tui.confirmation+7]
# r[verify installer.tui.ascii-rendering]
# r[verify installer.tui.error-reboot]
# r[verify installer.write.expand-root]
# r[verify image.growth.service]
# r[verify image.boot.grub-uuids]
step5() {
    cat << 'MD'
## Step 5: ISO in a Full VM (VirtualBox)

This verifies the ISO boots correctly in a real UEFI VM environment, which
exercises the El Torito EFI boot path, GRUB, live-boot, and the automatic
TUI launch -- none of which are tested by the container-based tests.

1. Create a new VM in VirtualBox:
   - Type: Linux, Ubuntu (64-bit)
   - Enable EFI: Settings > System > Enable EFI
   - RAM: 2048 MB minimum
   - Create a virtual hard disk: 10 GB minimum (VDI, dynamically
     allocated)
   - Attach the ISO as an optical disc (Settings > Storage > add optical
     drive)
   - **Disconnect the network adapter** (Settings > Network > uncheck
     "Enable Network Adapter") to verify offline installation works.

2. Boot the VM from the ISO.

3. Observe the boot sequence:
   - GRUB menu should appear (or auto-select after timeout).
   - The live environment should boot to a console.
   - The TUI installer should launch automatically on the primary
     console.

4. Walk through the installer:
   - Select the virtual disk.
   - Choose any encryption mode (keyfile recommended for VMs without
     TPM).
   - Set a hostname and password.
   - Skip Tailscale (leave empty).
   - Confirm and let the install complete.

5. Remove the ISO from the virtual optical drive and reboot the VM.

6. Verify the installed system boots:
   - GRUB menu appears.
   - Kernel loads and systemd starts services.
   - Login prompt appears (if encrypted, LUKS should auto-unlock via
     keyfile or prompt for the recovery passphrase).
   - Log in as `ubuntu` with the password you set.
   - Run `systemctl --failed` and confirm no unexpected failed units.
   - Run `cat /etc/bes/image-variant` and confirm it matches your
     encryption choice (`luks-tpm`, `luks-keyfile`, or `plain`).
   - Run `df -h /` and confirm the root filesystem has been expanded
     beyond the base image size.
   - Run `btrfs subvolume list /` and confirm `@` and `@postgres`
     subvolumes exist.

**Acceptance criteria**: the ISO boots in EFI mode without network, the
installer completes successfully, the installed system boots unattended (no
manual LUKS passphrase entry for keyfile mode), and the basic system health
checks above pass.

MD
}
step5

# r[verify iso.config-partition]
# r[verify installer.config.location]
# r[verify installer.mode.prefilled]
step6() {
    cat << 'MD'
## Step 6: USB Configuration -- Prefilled Defaults

This verifies that the BESCONF partition is writable after `dd` and that a
configuration file correctly pre-fills the TUI defaults.

1. Write the ISO to the USB drive:

   ```
   sudo dd if=output/amd64/bes-installer-amd64.iso of=/dev/sdX bs=4M status=progress
   sync
   ```

2. Unplug and re-plug the USB drive. Mount the BESCONF partition:

   ```
   sudo mount /dev/sdX3 /mnt    # partition number may vary; look for label BESCONF
   ```

3. Edit the configuration file to set defaults without enabling auto mode:

   ```
   cat | sudo tee /mnt/bes-install.toml << 'EOF'
   disk-encryption = "keyfile"
   hostname = "prefill-test"
   timezone = "Pacific/Auckland"
   EOF
   ```

4. Unmount: `sudo umount /mnt`

5. Boot a machine from the USB (or use the VirtualBox VM with the USB
   passed through, or attach the raw USB image file).

6. When the TUI launches, verify:
   - The disk encryption screen defaults to "Full-disk encryption, not
     bound to hardware" (keyfile).
   - The hostname screen defaults to "Static hostname" with
     `prefill-test` pre-filled.
   - The timezone screen defaults to `Pacific/Auckland`.
   - All values are editable (the user can change them).

7. You can either complete the install or just exit (Ctrl+C). The point
   of this step is to verify the config is loaded, not to complete an
   install.

**Acceptance criteria**: the config file is read from BESCONF and all
specified fields appear as defaults in the TUI. The user can still
override every value.

MD
}
step6

# r[verify installer.mode.auto+4]
# r[verify installer.config.auto]
# r[verify installer.config.disk-encryption+2]
# r[verify installer.config.disk]
# r[verify installer.config.hostname]
# r[verify installer.config.password]
# r[verify installer.finalise.hostname]
# r[verify installer.finalise.password]
# r[verify iso.usb]
step7() {
    cat << 'MD'
## Step 7: USB Configuration -- Automatic Mode

This verifies that `auto = true` drives a fully unattended install from
USB.

1. Mount the BESCONF partition again and write an automatic config:

   ```
   cat | sudo tee /mnt/bes-install.toml << 'EOF'
   auto = true
   disk-encryption = "keyfile"
   disk = "largest"
   hostname = "auto-test"
   password = "testpass"
   EOF
   ```

2. Unmount: `sudo umount /mnt`

3. Boot the target machine from the USB.

4. Observe: the installer should proceed without any interactive prompts.
   Progress is displayed on the console. The machine reboots
   automatically on success.

5. After reboot, verify the installed system:
   - Hostname is `auto-test` (`hostnamectl`).
   - Log in with password `testpass` (should not prompt for password
     change).
   - Variant is `luks-keyfile` (`cat /etc/bes/image-variant`).

**Acceptance criteria**: the install completes with zero human
interaction. The installed system reflects the configuration from the
TOML file.

MD
}
step7

# r[verify iso.hybrid]
# r[verify installer.encryption.tpm-enroll+3]
# r[verify image.firewall.policy]
# r[verify image.firewall.ssh]
# r[verify image.tailscale.service-enabled]
step8() {
    cat << 'MD'
## Step 8: Bare-Metal Hardware Boot

1. Write the ISO to a USB drive (if not already done in Step 6).
2. Boot a real UEFI machine from the USB.
3. Run through the interactive installer, selecting TPM encryption if a
   TPM is available.
4. Reboot into the installed system.
5. Verify:
   - System boots unattended (no passphrase prompt if TPM was selected).
   - `systemctl --failed` shows no unexpected failures.
   - Network connectivity works (DHCP, DNS resolution).
   - `sudo ufw status` shows the expected firewall rules.

**Acceptance criteria**: the system boots and operates normally on real
hardware. If TPM encryption was selected, the disk unlocks automatically
via the TPM.

MD
}
step8

# r[verify image.variant.types+3]
# r[verify image.boot.grub-install]
# r[verify image.boot.grub-timeout]
# r[verify image.boot.grub-cmdline]
# r[verify image.boot.grub-uuids]
# r[verify image.growth.service]
# r[verify image.growth.script+2]
step9() {
    cat << 'MD'
## Step 9: Direct Image Write Boot

This verifies that the disk images boot correctly when written directly to
a disk, without using the ISO installer.

1. Write the cloud image to a spare disk or VM virtual disk:

   ```
   zstd -d output/amd64/cloud/*.raw.zst --stdout | sudo dd of=/dev/sdX bs=4M status=progress
   sync
   ```

2. Boot from the disk (or attach it to a VM with at least 10 GB total
   disk size so the growth service has room to expand).

3. Verify:
   - GRUB menu appears with a 5-second timeout.
   - The system boots to a login prompt.
   - Log in as `ubuntu` with password `bes` (will be forced to change it).
   - `cat /etc/bes/image-variant` shows `cloud` (this is the build-time
     cloud image, not an installer-produced system).
   - `df -h /` shows the root filesystem has been expanded beyond the
     base image size.
   - `btrfs subvolume list /` shows `@` and `@postgres`.

4. Repeat with the metal image.

**Acceptance criteria**: both cloud and metal images boot from a raw disk
write. The growth service expands the root filesystem. The metal image
boots without prompting for a passphrase.

MD
}
step9

# r[verify installer.config.recovery-passphrase]
# r[verify installer.config.save-recovery-keys]
# r[verify installer.besconf.writable-detection]
# r[verify installer.besconf.failure-log]
step10() {
    cat << 'MD'
## Step 10: BESCONF Interaction and Recovery Passphrase

This verifies the BESCONF writable-detection, failure-log rotation,
`recovery-passphrase` config field, and `save-recovery-keys` config field.
These features require a real (or realistic) BESCONF partition that the
installer can remount read-write, so they cannot be fully tested in
unit tests.

### 10a: Recovery passphrase and save-recovery-keys (auto mode)

1. Mount the BESCONF partition on the USB drive prepared in Step 6:

   ```
   sudo mount /dev/sdX3 /mnt    # partition label BESCONF
   ```

2. Write a config that uses a pre-determined recovery passphrase and
   enables saving recovery keys:

   ```
   cat | sudo tee /mnt/bes-install.toml << 'EOF'
   auto = true
   disk-encryption = "keyfile"
   disk = "largest"
   hostname = "recovery-test"
   password = "testpass"
   recovery-passphrase = "this-is-a-test-passphrase-that-is-long-enough"
   save-recovery-keys = true
   EOF
   ```

3. Remove any leftover files from previous runs:

   ```
   sudo rm -f /mnt/recovery-keys.txt /mnt/installer-failed.log /mnt/installer-failed.log.old
   ```

4. Unmount: `sudo umount /mnt`

5. Boot the target machine from the USB and let the automatic install
   complete. The installer should display the pre-determined passphrase
   (`this-is-a-test-passphrase-that-is-long-enough`) on the recovery
   passphrase screen, not a random diceware passphrase.

6. After reboot, remove the USB and mount the BESCONF partition on
   your workstation:

   ```
   sudo mount /dev/sdX3 /mnt
   cat /mnt/recovery-keys.txt
   ```

7. Verify the `recovery-keys.txt` file contains one line with three
   tab-separated fields:
   - The passphrase (`this-is-a-test-passphrase-that-is-long-enough`).
   - A UUID (the root partition UUID).
   - A machine serial number or the literal string `unknown`.

8. Verify the installed system unlocks with the pre-determined
   passphrase: boot the installed disk and when prompted for the LUKS
   recovery passphrase (e.g. after removing the keyfile or on a
   different machine), enter
   `this-is-a-test-passphrase-that-is-long-enough`.

**Acceptance criteria**: the installer uses the provided passphrase
instead of generating one, and `recovery-keys.txt` is written to BESCONF
with the correct format.

### 10b: BESCONF writable detection and failure-log rotation

1. Mount the BESCONF partition and create a fake failure log from a
   "previous run":

   ```
   sudo mount /dev/sdX3 /mnt
   echo "fake previous failure" | sudo tee /mnt/installer-failed.log
   ```

2. Write a config that will cause the installer to fail (e.g. specify a
   disk that does not exist):

   ```
   cat | sudo tee /mnt/bes-install.toml << 'EOF'
   auto = true
   disk-encryption = "keyfile"
   disk = "/dev/sdZZZ"
   hostname = "fail-test"
   password = "testpass"
   EOF
   ```

3. Unmount: `sudo umount /mnt`

4. Boot the target machine from the USB. The installer should fail
   because `/dev/sdZZZ` does not exist.

5. Remove the USB, mount BESCONF on your workstation, and verify:

   ```
   sudo mount /dev/sdX3 /mnt
   ls -la /mnt/installer-failed.log /mnt/installer-failed.log.old
   cat /mnt/installer-failed.log.old
   cat /mnt/installer-failed.log
   ```

   - `installer-failed.log.old` should contain "fake previous failure"
     (the file from sub-step 1 was rotated).
   - `installer-failed.log` should contain the actual installer log from
     the failed run (look for error messages about the missing disk).

6. Clean up: `sudo umount /mnt`

**Acceptance criteria**: the installer detects BESCONF as writable,
rotates the existing failure log to `.old`, and writes the new failure
log on error.

MD
}
step10

checklist() {
    cat << 'MD'
## Completion Checklist

After completing all steps, confirm:

- [ ] Step 1: Images and ISO built successfully.
- [ ] Step 2: Automated tests passed.
- [ ] Step 3: All container install scenarios passed (including metal).
- [ ] Step 4: Interactive TUI works, Tailscale auth key accepted.
- [ ] Step 5: ISO boots in VM, installed system is healthy.
- [ ] Step 6: BESCONF prefilled defaults appear in TUI.
- [ ] Step 7: Automatic mode installs without interaction.
- [ ] Step 8: Bare-metal hardware boot works.
- [ ] Step 9: Direct image write boots (cloud and metal).
- [ ] Step 10a: Recovery passphrase accepted, recovery-keys.txt written.
- [ ] Step 10b: Failure log rotated and written on BESCONF.
MD
}
checklist

}

if [ "${1:-}" = "--check" ]; then
    EXPECTED="$(generate)"
    if [ ! -f "$OUTPUT" ]; then
        echo "ERROR: $OUTPUT does not exist. Run: scripts/gen-manual-testing.sh > docs/manual-testing.md"
        exit 1
    fi
    ACTUAL="$(cat "$OUTPUT")"
    if [ "$EXPECTED" != "$ACTUAL" ]; then
        echo "ERROR: docs/manual-testing.md is out of date."
        echo "Run: scripts/gen-manual-testing.sh > docs/manual-testing.md"
        diff --unified <(echo "$ACTUAL") <(echo "$EXPECTED") || true
        exit 1
    fi
    echo "docs/manual-testing.md is up to date."
    exit 0
fi

generate
